# Copyright 2025 Entalpic
name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read Python version from .python-version
        id: python_version
        run: |
          PYTHON_VERSION=$(cat .python-version)
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Install project dependencies
        run: |
         uv sync --all-extras

      - name: Run linting
        run: |
          uv run ruff check

      - name: Run pytest tests
        run: |
          uv run pytest
